version: "3"

services:
  app:
    image: redcap-support-api/redcap-support-api:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "uvicorn src.rss.server_main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - env/.env.dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      REDIS_IP: queue
      REDIS_PORT: 6379
    ports:
      - "8002:8000"
    volumes:
      - .:/code
    depends_on:
      - db
      - queue

  worker:
    image: redcap-support-api-worker/redcap-support-api-worker:dev
    build:
      context: .
      dockerfile: Dockerfile.worker.dev
    command: bash -c "arq src.rss.worker.WorkerSettings --watch ./src"
    env_file:
      - env/.env.dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      REDIS_IP: queue
      REDIS_PORT: 6379
    volumes:
      - .:/code
    depends_on:
      - db
      - queue

  db:
    image: postgres:15
    env_file:
      - env/.env.dev
    ports:
      - "5434:5432"
    volumes:
      - rss-data-dev:/var/lib/postgresql/data

  queue:
    image: redis:7.2.3
    env_file:
      - env/.env.dev
    ports:
      - "6381:6379"
    volumes:
      - rss-queue-dev:/data

volumes:
  rss-data-dev:
  rss-queue-dev:
