"""Add Authorized User Table

Revision ID: 0adba5aa27d8
Revises: 6d340c740267
Create Date: 2023-11-03 13:17:34.049818

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0adba5aa27d8"
down_revision = "6d340c740267"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_id_unique_constraint", "user", ["user_id"])

    op.create_table(
        "authorized_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("viewer", sa.Boolean(), nullable=False),
        sa.Column("editor", sa.Boolean(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("modified", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_id_unique_constraint", "user", type_="unique")
    op.drop_table("authorized_user")
    # ### end Alembic commands ###
