"""Add Report Calculated Fields

Revision ID: 1e599fd8a527
Revises: 5dccfde0385d
Create Date: 2023-10-13 12:32:10.678454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1e599fd8a527"
down_revision = "5dccfde0385d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report",
        sa.Column(
            "calculated_event_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "report",
        sa.Column(
            "calculated_instrument_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report", "calculated_event_fields")
    op.drop_column("report", "calculated_instrument_fields")
    # ### end Alembic commands ###
