"""add unique constraint to event/instrument tables

Revision ID: 3199a0f7f49c
Revises: 834d17001485
Create Date: 2023-12-14 13:34:17.700590

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "3199a0f7f49c"
down_revision = "834d17001485"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "event_record_id_repeat_instance_event_id_instrument_id_key",
        "event",
        ["record_id", "repeat_instance", "event_id", "instrument_id"],
    )
    op.create_unique_constraint(
        "instrument_record_id_repeat_instance_event_id_instrument_id_key",
        "instrument",
        ["record_id", "repeat_instance", "event_id", "instrument_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "instrument_record_id_repeat_instance_event_id_instrument_id_key",
        "instrument",
        type_="unique",
    )
    op.drop_constraint(
        "event_record_id_repeat_instance_event_id_instrument_id_key",
        "event",
        type_="unique",
    )
    # ### end Alembic commands ###
