"""Rework Admins into Authorizations Table

Revision ID: 834d17001485
Revises: 0adba5aa27d8
Create Date: 2023-11-03 15:34:51.582010

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "834d17001485"
down_revision = "0adba5aa27d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("authorized_user", sa.Column("admin", sa.Boolean(), nullable=False))
    op.drop_column("user", "is_admin")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.drop_column("authorized_user", "admin")
    # ### end Alembic commands ###
