"""Add relationships for events and instruments

Revision ID: dc14eebba280
Revises: d9c6047a1208
Create Date: 2023-09-18 15:39:12.129188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc14eebba280"
down_revision = "d9c6047a1208"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_event_project_instrument_association",
        sa.Column("project_event_id", sa.Integer(), nullable=False),
        sa.Column("project_instrument_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_event_id"],
            ["project_event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_instrument_id"],
            ["project_instrument.id"],
        ),
        sa.PrimaryKeyConstraint("project_event_id", "project_instrument_id"),
    )
    op.drop_table("event_instrument_association")
    op.add_column("event", sa.Column("event_id", sa.Integer(), nullable=False))
    op.add_column("event", sa.Column("instrument_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "event", "project_instrument", ["instrument_id"], ["id"]
    )
    op.create_foreign_key(None, "event", "project_event", ["event_id"], ["id"])
    op.drop_column("event", "form_name")
    op.drop_column("event", "event_name")
    op.add_column("instrument", sa.Column("event_id", sa.Integer(), nullable=False))
    op.add_column(
        "instrument", sa.Column("instrument_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "instrument", "project_event", ["event_id"], ["id"])
    op.create_foreign_key(
        None, "instrument", "project_instrument", ["instrument_id"], ["id"]
    )
    op.drop_column("instrument", "form_name")
    op.drop_column("instrument", "event_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instrument",
        sa.Column("event_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "instrument",
        sa.Column("form_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )

    op.drop_column("instrument", "instrument_id")
    op.drop_column("instrument", "event_id")
    op.add_column(
        "event",
        sa.Column("event_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "event",
        sa.Column("form_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )

    op.drop_column("event", "instrument_id")
    op.drop_column("event", "event_id")
    op.create_table(
        "event_instrument_association",
        sa.Column(
            "project_event_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "project_instrument_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["project_event_id"],
            ["project_event.id"],
            name="event_instrument_association_project_event_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["project_instrument_id"],
            ["project_instrument.id"],
            name="event_instrument_association_project_instrument_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "project_event_id",
            "project_instrument_id",
            name="event_instrument_association_pkey",
        ),
    )
    op.drop_table("project_event_project_instrument_association")
    # ### end Alembic commands ###
